package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/hanzili/oniji-go-server/utils"
)

// OnijiPing is the resolver for the ONIJI_Ping field.
func (r *queryResolver) OnijiPing(ctx context.Context) (*string, error) {
	return utils.String("pong"), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
