package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hanzili/oniji-go-server/constants"
	"github.com/hanzili/oniji-go-server/graph/model"
	"github.com/hanzili/oniji-go-server/models"
	"github.com/hanzili/oniji-go-server/repositories"
)

// OnijiCreateSession is the resolver for the ONIJI_CreateSession field.
func (r *mutationResolver) OnijiCreateSession(ctx context.Context, input model.OnijiCreateSessionInput) (*model.OnijiSessionReponse, error) {
	userId := ctx.Value(constants.CtxKeyUserId).(string)

	session := &models.Session{
		Mood:        models.Mood(input.Mood),
		SessionType: models.SessionType(input.SessionType),
		HasScent:    input.HasScent,
		UserId:      uuid.MustParse(userId),
	}
	// find the mapping for the session
	mockMusic := &models.Music{
		Name:     "mock",
		Url:      "mock",
		Duration: 120, // seconds
	}
	session.Music = *mockMusic

	// start the session
	// start detecting brave wave
	// start defusing the scent
	// start the music

	// get current time
	timeNow := time.Now()
	session.StartTime = &timeNow
	err := repositories.SessionRepo.Create(session)
	if err != nil {
		return nil, err
	}

	return &model.OnijiSessionReponse{
		Session: convertToGqlSession(session),
	}, nil
}

// OnijiEndSession is the resolver for the ONIJI_EndSession field.
func (r *mutationResolver) OnijiEndSession(ctx context.Context, input model.OnijiEndSessionInput) (*model.OnijiSessionReponse, error) {
	userId := ctx.Value(constants.CtxKeyUserId).(string)

	session, err := repositories.SessionRepo.GetById(input.ID)
	if err != nil {
		return nil, err
	}

	if userId != session.UserId.String() {
		errorCode := 401
		errorMsg := "You can only end session of your own"
		return &model.OnijiSessionReponse{
			ErrorCode:    &errorCode,
			ErrorMessage: &errorMsg,
			Session:      nil,
		}, nil
	}

	// stop detecting brave wave
	// stop defusing the scent
	// stop the music

	timeNow := time.Now()
	session.EndTime = &timeNow
	err = repositories.SessionRepo.Update(session)
	if err != nil {
		return nil, err
	}

	return &model.OnijiSessionReponse{
		Session: convertToGqlSession(session),
	}, nil
}

// OnijiGetSessions is the resolver for the ONIJI_GetSessions field.
func (r *queryResolver) OnijiGetSessions(ctx context.Context) (*model.OnijiSessionsResponse, error) {
	userId := ctx.Value(constants.CtxKeyUserId).(string)
	sessions, err := repositories.SessionRepo.GetAllSessionByUserId(uuid.MustParse(userId))
	if err != nil {
		return nil, err
	}

	return &model.OnijiSessionsResponse{
		Sessions:   convertToGqlSessions(sessions),
		TotalCount: len(sessions), //TODO: return total count
	}, nil
}

// OnijiGetSession is the resolver for the ONIJI_GetSession field.
func (r *queryResolver) OnijiGetSession(ctx context.Context, input model.OnijiGetSessionInput) (*model.OnijiSessionReponse, error) {
	session, err := repositories.SessionRepo.GetById(input.ID)
	if err != nil {
		return nil, err
	}

	return &model.OnijiSessionReponse{
		Session: convertToGqlSession(session),
	}, nil
}
