/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cAh4ZOdzCqJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Image from 'next/image'
import CodeIconSvg from '@/public/logo.png'

export function LandingPage(): JSX.Element {
  return (
    <div className="flex flex-col min-h-[100dvh] a">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        {/* <Link href="/" className="flex items-center justify-center">
          <CodeIcon className="h-24 w-32" />
          <span className="sr-only">Oniji</span>
        </Link> */}
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#features" className="text-sm font-medium hover:underline underline-offset-4">
            Features
          </Link>
          <Link href="#partners" className="text-sm font-medium hover:underline underline-offset-4">
            Partners
          </Link>
          <Link href="#contact" className="text-sm font-medium hover:underline underline-offset-4">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 justify-center items-center">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex justify-center items-center bg-background">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_550px] lg:gap-12 xl:grid-cols-[1fr_650px]">
              <div className="flex flex-col justify-center space-y-4 text-foreground">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none text-foreground mb-5">
                    Recharge Your Mind with Oniji
                  </h1>
                  <p className="max-w-[600px] text-foreground/80 md:text-xl mb-5">
                    Experience a unique meditation session in our futuristic egg-shaped booth, designed to help you
                    relax and recharge in the modern world.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="https://cal.com/oniji"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  >
                    Book Now
                  </Link>
                  <Link
                    href="#contact"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium text-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <img
                src="/meditate.gif"
                width="550"
                height="550"
                alt="Oniji Booth"
                className="hidden lg:block mx-auto aspect-square overflow-hidden rounded-xl object-cover lg:order-last w-64 max-w-full"              />
            </div>
          </div>
        </section>
        <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6 mx-auto">
            <div className="text-center mb-12">
              <div className="inline-block rounded-lg bg-background px-3 py-1 text-sm text-primary mb-4">Key Features</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl mb-4">Unlock Your Mind&apos;s Potential</h2>
              <p className="text-muted-foreground text-sm sm:text-base md:text-lg max-w-2xl mx-auto">
                Our futuristic egg-shaped booth uses cutting-edge technology to guide you through a personalized
                meditation session, helping you recharge.
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <Image
                src="/booth.webp"
                alt="Oniji Features"
                width={450}
                height={450}
                className="w-full max-w-[450px] mx-auto rounded-xl object-cover object-center md:order-last"
              />
              <div className="space-y-8">
                {[
                  {
                    title: "Brainwave Detection",
                    description: "Our booth uses advanced sensors to detect your brainwaves, allowing us to customize your meditation experience."
                  },
                  {
                    title: "Immersive Sensations",
                    description: "Experience a symphony of sights, sounds, and scents that guide you through your meditation session."
                  },
                  {
                    title: "Personalized Therapy",
                    description: "Our experts analyze your brainwave data to provide a customized meditation experience tailored to your needs."
                  }
                ].map((feature, index) => (
                  <div key={index} className="flex items-start space-x-4">
                    <div className="flex-shrink-0 w-12 h-12 rounded-full flex items-center justify-center">
                      <span className="text-2xl text-primary font-bold rounded-full">{index + 1}</span>
                    </div>
                    <div>
                      <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                      <p className="text-muted-foreground">{feature.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section id="partners" className="w-full py-12 md:py-24 lg:py-32 bg-background flex justify-center items-center">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-xl text-primary">Our Partners</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Collaborating with Industry Leaders</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Oniji has partnered with renowned experts and hardware providers to bring you the best possible
                  meditation experience.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col items-center justify-center space-y-2">
                <Image
                  src="/mcgill.png"
                  width={120}
                  height={120}
                  alt="McGill University"
                  className="aspect-square object-contain"
                />
                <p className="text-lg font-bold">McGill University</p>
                <p className="text-muted-foreground text-center ">Collaboration with leading psychology experts</p>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <Image
                  src="/neurosity.png"
                  width={120}
                  height={120}
                  alt="Neurosity"
                  className="aspect-square object-contain"
                />
                <p className="text-lg font-bold">Neurosity</p>
                <p className="text-muted-foreground text-center ">Cutting-edge brainwave detection technology</p>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <Image
                  src="/meditation.png"
                  width={120}
                  height={120}
                  alt="Published Papers"
                  className="aspect-square object-contain"
                />
                <p className="text-lg font-bold">Based on Research Papers</p>
                <p className="text-muted-foreground">Research-backed meditation techniques</p>
              </div>
            </div>
          </div>
        </section>
        {/* <section id="about" className="w-full py-12 md:py-24 lg:py-32 bg-muted flex justify-center items-center">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-primary">About Oniji</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Recharge Your Mind, Rejuvenate Your Life
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Oniji was founded with the mission to help people recharge and rejuvenate in the modern, fast-paced
                  world. Our cutting-edge meditation booth combines the latest technology, research-backed techniques,
                  and a focus on holistic well-being to provide a truly unique experience.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Oniji About"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Mission-Driven</h3>
                      <p className="text-muted-foreground">
                        Oniji was founded with the goal of helping people recharge and rejuvenate in the modern world.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Holistic Approach</h3>
                      <p className="text-muted-foreground">
                        We combine the latest technology, research-backed techniques, and a focus on overall well-being
                        to provide a truly unique meditation experience.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Innovative Solutions</h3>
                      <p className="text-muted-foreground">
                        Our futuristic egg-shaped booth is designed to transport you to a state of deep relaxation and
                        rejuvenation.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section> */}
        <section id="contact" className="w-full py-12 md:py-24 lg:py-32 border-t flex justify-center items-center bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Experience the Future of Meditation
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Book your session with Oniji and unlock the power of personalized meditation.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex gap-2">
                <Input 
                  type="email" 
                  placeholder="Enter your email" 
                  className="max-w-lg flex-1 bg-background border-2 border-primary focus:ring-2 focus:ring-primary" 
                />
                <Link href="https://cal.com/oniji">
                  <Button type="button">Book Now</Button>
                </Link>
              </form>
              <p className="text-xs text-muted-foreground">
                Sign up to get notified about our latest updates.{" "}
                <Link href="#" className="underline underline-offset-2">
                  Terms &amp; Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Oniji. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4">
            Privacy Policy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4">
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CodeIcon(props: any) {
  return (
    <Image
      src={CodeIconSvg}
      alt="Code Icon"
      width={24}
      height={24}
      {...props}
    />
  )
}
