import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { getClient } from "@/lib/apollo-client";
import { ApolloWrapper } from "./ApolloWrapper";
import { PING } from "@/lib/gql";

const inter = Inter({ subsets: ["latin"] });
getClient()
  .query({ query: PING })
  .then((result) => console.log(result));

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ApolloWrapper>
              <ModeToggle />
              {children}
            </ApolloWrapper>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
