import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/wrappers/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { ApolloWrapper } from "@/components/wrappers/apollo-wrapper";
import { getDictionary } from "@/lib/dictionaries/dictionaries";
import { DictionaryProvider } from "@/components/wrappers/dictionary-wrapper";
import LanguageSwitcher from "@/components/language-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const dict = await getDictionary(params.lang);

  return (
    <>
      <html lang={params.lang} suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ApolloWrapper>
              <DictionaryProvider dict={dict}>
                <div className="h-screen p-4 bg-background">
                  <div className="flex items-center justify-between">
                    <ModeToggle />
                    <LanguageSwitcher locale={params.lang} />
                  </div>
                  {children}
                </div>
              </DictionaryProvider>
            </ApolloWrapper>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
